(add-to-list 'load-path "~/.emacs.d/emacs-tools/pdb-helpers/")
(add-to-list 'load-path "~/.emacs.d/emacs-tools/window/")
(add-to-list 'load-path "~/.emacs.d/emacs-tools/org/")
(require 'pdb-breakpoints-marker)
(require 'custom-window-resize)
(require 'custom-org-agenda)
(require 'org-keywords)
